# Generated by Django 4.1.7 on 2023-02-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderplaced", old_name="order_date", new_name="orderd_date",
        ),
        migrations.RemoveField(model_name="cart", name="counts",),
        migrations.AddField(
            model_name="cart",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
