# Generated by Django 4.1.7 on 2023-10-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MYProductList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("zipcode", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "shippingcost",
                    models.PositiveIntegerField(blank=True, default=20, null=True),
                ),
            ],
        ),
    ]
