# Generated by Django 4.1.7 on 2023-09-14 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_category_image_alter_product_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="category", new_name="categories",
        ),
    ]
