# Generated by Django 4.1.7 on 2023-09-14 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_rename_category_product_categories"),
    ]

    operations = [
        migrations.AlterModelOptions(name="product", options={"ordering": ("title",)},),
    ]
