# Generated by Django 4.1.7 on 2023-09-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_product_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="categories", new_name="category",
        ),
    ]
