# Generated by Django 4.1.7 on 2023-09-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_rename_categories_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, null=True, upload_to="brand")),
                (
                    "category",
                    models.ManyToManyField(blank=True, null=True, to="app.category"),
                ),
            ],
        ),
    ]
