# Generated by Django 4.1.7 on 2023-09-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_product_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderplaced",
            name="status",
            field=models.CharField(
                choices=[
                    ("Accepted", "Accepted"),
                    ("Packed", "Packed"),
                    ("On The Way", "On The Way"),
                    ("Delivered", "Delivered"),
                    ("Cancel", "Cancel"),
                ],
                default="orderd_date",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="discounted_price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
