# Generated by Django 4.1.7 on 2023-10-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_alter_orderplaced_price_per_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="contact_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
