# Generated by Django 4.1.7 on 2023-10-17 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_customer_address_customer_contact_no"),
    ]

    operations = [
        migrations.RemoveField(model_name="customer", name="locality",),
    ]
