# Generated by Django 4.1.7 on 2023-10-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_alter_orderplaced_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Productcolor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "shortform",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.ManyToManyField(blank=True, null=True, to="app.productcolor"),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.ManyToManyField(blank=True, null=True, to="app.productsize"),
        ),
    ]
