# Generated by Django 4.1.7 on 2023-10-19 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_alter_product_color_alter_product_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="color",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.productcolor",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cart",
            name="size",
            field=models.ForeignKey(
                blank=True,
                default=12,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.productsize",
            ),
            preserve_default=False,
        ),
    ]
