# Generated by Django 4.1.7 on 2023-10-19 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_cart_color_cart_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.productcolor",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.productsize",
            ),
        ),
    ]
