# Generated by Django 4.1.7 on 2023-10-20 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_alter_cart_color_alter_cart_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderplaced",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app.productcolor",
            ),
        ),
        migrations.AddField(
            model_name="orderplaced",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app.productsize",
            ),
        ),
    ]
